const models=[['hy-world','HY-World 1.5'],['lingbot','LingBot-World-v2'],['matrix-game','Matrix-Game-2'],['causal-forcing','Causal-Forcing']];
const methods=[['bf16','BF16','Reference'],['qvg','QVG','2-bit KV cache'],['quantwm','QuantWM','Ours']];
let controllers=[];
function showModel(id,name){controllers.forEach(c=>c.destroy());controllers=[];document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===id)));const gallery=document.querySelector('#gallery');gallery.innerHTML='';for(let sample=1;sample<=({
  'hy-world': 5,
  'lingbot': 5,
  'matrix-game': 4,
  'causal-forcing': 4
}[id]);sample++){const row=document.createElement('article');row.className='example';row.innerHTML=`<div class="example-head"><h3>${name}</h3><span class="sample">Example 0${sample}</span></div><div class="videos">${methods.map(([key,label,note])=>`<figure><figcaption><span>${label} <small>${note}</small></span><button class="expand" aria-label="Expand ${label} video" title="Fullscreen">⛶</button></figcaption><video muted playsinline preload="metadata" poster="assets/${id}-${sample}-${key}.jpg" src="assets/${id}-${sample}-${key}.mp4" aria-label="${name}, example ${sample}, ${label}"></video></figure>`).join('')}</div><div class="controls"><button class="play" aria-label="Play all three videos">▶ Play</button><button class="restart" title="Restart all three videos" aria-label="Restart all three videos">↺</button><input class="seek" type="range" min="0" max="1000" value="0" aria-label="Seek all three videos"><span class="time">0:00 / 0:00</span><select aria-label="Playback speed"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option></select></div><p class="status" role="status"></p>`;gallery.append(row);controllers.push(control(row));}}
function control(row){const videos=[...row.querySelectorAll('video')],button=row.querySelector('.play'),seek=row.querySelector('.seek'),status=row.querySelector('.status');let playing=false,disposed=false,starting=false;const duration=()=>Math.min(...videos.map(v=>v.duration||Infinity));const fmt=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;function pause(){playing=false;videos.forEach(v=>v.pause());button.textContent='▶ Play';button.setAttribute('aria-label','Play all three videos');}async function play(){if(starting)return;starting=true;controllers.forEach(c=>{if(c.row!==row)c.pause()});status.textContent='Loading videos…';try{await Promise.all(videos.map(v=>v.readyState>=3?Promise.resolve():new Promise((resolve,reject)=>{const done=()=>{clearTimeout(timer);v.removeEventListener('canplay',done);resolve()};const timer=setTimeout(()=>{v.removeEventListener('canplay',done);reject(new Error('load'))},20000);v.addEventListener('canplay',done);v.load()})));if(disposed)return;if(videos[0].currentTime>=duration()-.1)videos.forEach(v=>v.currentTime=0);await Promise.all(videos.map(v=>v.play()));if(disposed){pause();return}playing=true;button.textContent='❚❚ Pause';button.setAttribute('aria-label','Pause all three videos');status.textContent='';}catch{pause();status.textContent='Could not play the videos. Please try again.'}finally{starting=false}}
button.onclick=()=>playing?pause():play();row.querySelector('.restart').onclick=()=>{pause();videos.forEach(v=>v.currentTime=0);play()};seek.oninput=()=>{const d=duration();if(Number.isFinite(d))videos.forEach(v=>v.currentTime=Number(seek.value)/1000*d)};row.querySelector('select').onchange=e=>videos.forEach(v=>v.playbackRate=Number(e.target.value));row.querySelectorAll('.expand').forEach((b,i)=>b.onclick=()=>{const v=videos[i];if(v.requestFullscreen)v.requestFullscreen().catch(()=>{});else if(v.webkitEnterFullscreen)v.webkitEnterFullscreen()});videos.forEach(v=>v.addEventListener('error',()=>{pause();status.textContent='Video unavailable. Reload the page to retry.'}));const tick=setInterval(()=>{const d=duration(),t=videos[0].currentTime;if(Number.isFinite(d)){seek.value=String(t/d*1000);row.querySelector('.time').textContent=`${fmt(t)} / ${fmt(d)}`}if(playing){if(t>=d-.08||videos.some(v=>v.ended)){pause();return}if(videos.some(v=>v.readyState<3)){pause();status.textContent='Buffering — press Play to resume together.';return}videos.slice(1).forEach(v=>{if(Math.abs(v.currentTime-t)>.12)v.currentTime=t})}},100);return{row,pause,destroy(){disposed=true;pause();clearInterval(tick);videos.forEach(v=>{v.removeAttribute('src');v.load()})}}}
models.forEach(([id,name])=>{const b=document.createElement('button');b.dataset.id=id;b.textContent=name;b.setAttribute('aria-pressed','false');b.onclick=()=>showModel(id,name);document.querySelector('#model-tabs').append(b)});showModel(...models[0]);document.addEventListener('visibilitychange',()=>{if(document.hidden)controllers.forEach(c=>c.pause())});
